"""Milestone 2 -- mock EHR appointment API and mock insurance-eligibility API.

Both read/write the CSV tables generated by generate.py under
data/careflow/mock_ehr/. This is a mock: no real EHR/payer system is
contacted, and every record here is synthetic.
"""

import csv
from pathlib import Path

from app.config import settings


def _read_csv(path: Path) -> list[dict]:
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _write_csv(path: Path, rows: list[dict], fieldnames: list[str]) -> None:
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def get_available_slots(specialty_key: str, max_results: int = 5) -> list[dict]:
    """Mock EHR appointment API: list open appointment slots for a specialty."""
    path = settings.mock_ehr_dir / "appointments.csv"
    rows = _read_csv(path)
    matches = [
        r for r in rows
        if r["specialty_key"] == specialty_key and r["status"] == "available"
    ]
    matches.sort(key=lambda r: (r["slot_date"], r["slot_time"]))
    return matches[:max_results]


def book_appointment(appointment_id: str, patient_id: str) -> dict:
    """Mock EHR appointment API: book a previously-available slot for a patient."""
    path = settings.mock_ehr_dir / "appointments.csv"
    rows = _read_csv(path)
    fieldnames = list(rows[0].keys())
    target = next((r for r in rows if r["appointment_id"] == appointment_id), None)
    if target is None:
        return {"success": False, "error": f"No appointment found with id {appointment_id}."}
    if target["status"] != "available":
        return {"success": False, "error": f"Appointment {appointment_id} is not available (status={target['status']})."}

    target["status"] = "booked"
    target["patient_id"] = patient_id
    _write_csv(path, rows, fieldnames)
    return {"success": True, "appointment": target}


def check_eligibility(insurance_id: str) -> dict:
    """Mock insurance-eligibility API: look up coverage status by insurance ID."""
    path = settings.mock_ehr_dir / "eligibility.csv"
    rows = _read_csv(path)
    record = next((r for r in rows if r["insurance_id"] == insurance_id), None)
    if record is None:
        return {"found": False, "error": f"No eligibility record found for insurance ID {insurance_id}."}
    return {"found": True, "eligibility": record}
